### ISSUE TITLE
Layering issue with menus

### ISSUE THREAD

**Issue by RejDev** [primefaces/layouts#1]
Hello,
I noticed some small problems in the theme:
* z-index (999) Order for menuPanel and icons Button + SelectOneMenu
* Pixel shift in Firefox
* Search menu disappears when you click it to write
* in mobile browsers ( Android os, Devises: Galaxy S5, Galaxy S6, Galaxy A5):
    - Native browser + chrome: scroll very slow with the displayed left menu (especially if the submenus are displayed)
    - FireFox mobile: the left menu exits the screen when scroll, and it becomes difficult to see the entire menu if it exceeds the screen height.

Here are some screenshots:
![bug1](https://cloud.githubusercontent.com/assets/12255492/8629521/8c5e4c10-274b-11e5-80b7-d96876ec4025.png)
![bug2](https://cloud.githubusercontent.com/assets/12255492/8629520/8c59f458-274b-11e5-93b7-087badccf669.png)

In mobile Firefox:
![screenshot_2015-07-11-05-09-11](https://cloud.githubusercontent.com/assets/12255492/8632454/8f0a4f14-278b-11e5-96f3-384fe24a656e.png)

Thank you for this nice theme.

**Comment by mertsincan** [comment]
Thanks for the screenshots, we will work on it and get back to you.

**Comment by mertsincan** [comment]
> Pixel shift in Firefox

I couldn't replicated this issue on Firefox. What FF version are you using?

**Comment by cagataycivici** [comment]
Both are replicated, we'll fix these asap.

**Comment by cagataycivici** [comment]
These issues are fixed in combination with #9, #10 and #11. 

Target is 17th July for 1.0.1 modena release to address these.
