### ISSUE TITLE
Volt 2.1.1 + Primefaces 5.3.17 Execution error

### ISSUE THREAD

**Issue by lcanalesmayo** [primefaces/layouts#110]
Hi,

when I try to use "menu" component of Volt template I'm getting this error:

java.lang.NoSuchMethodError: org.primefaces.context.ApplicationContext.getConfig()Lorg/primefaces/config/PrimeConfiguration;

It happens with Volt 2.1.1 and Primefaces 5.3.X, but not with Volt 2.1 and Primefaces 5.3.X.

Forum link: http://forum.primefaces.org/viewtopic.php?f=29&t=47072&p=146297#p146297

Thanks in advance.

**Comment by mertsincan** [comment]
I think this issue is fixed on next version; https://github.com/primefaces/layouts/issues/106

**Comment by lcanalesmayo** [comment]
This isn't fixed.

I will open new issue...

**Comment by mertsincan** [comment]
I couldn't replicate this issue with new version. Please change the following files with new files;
- layout.js
- *MenuRenderer.java
- *Menu.java
- less files

**Comment by lcanalesmayo** [comment]
It worked!!

Thanks.
