### ISSUE TITLE
Volt 2.1 + Primefaces 6.0.4 Css loading error

### ISSUE THREAD

**Issue by lcanalesmayo** [primefaces/layouts#111]
Hi,

when I try to use "menu" component of Volt template I'm getting this error:

Unable to find resource primefaces, primefaces.css

CSS files are not loaded. It happens with Volt 2.1 and Primefaces 6.0.X, but not with Volt 2.1 and Primefaces 5.3.X.

Forum link: http://forum.primefaces.org/viewtopic.php?f=29&t=47073&p=146153#p146153

Thanks in advance.

**Comment by mertsincan** [comment]
I think this issue is fixed on next version; https://github.com/primefaces/layouts/issues/106
