### ISSUE TITLE
Modena + Prime NG Growl has wrong colors, always "info"

### ISSUE THREAD

**Issue by xadhoom** [primefaces/layouts#113]
(forwarded from forum)

While playing with growl messages, I found that the color is always as "info" level, but in CSS there're the correct colors for error and so on.

Happens also on primeng+modena demo. On primeui+modena demo works ok.

**Comment by mertsincan** [comment]
Please try;
```
    .ui-growl-image-info {color: #03A9F4}
    .ui-growl-image-warn {color: #F9BF08}
    .ui-growl-image-error {color: #F03369}
    .ui-growl-image-info + .ui-growl-message { color: #03A9F4 !important; }
    .ui-growl-image-warn + .ui-growl-message { color: #F9BF08 !important; }
    .ui-growl-image-error + .ui-growl-message { color: #F03369 !important; }
```

**Comment by xadhoom** [comment]
well, looking into the theme.css seems already done:

.ui-growl-image-info {
  color: #03a9f4;
}
.ui-growl-image-warn {
  color: #f9bf08;
}
.ui-growl-image-error {
  color: #f03369;
}
.ui-growl-image-info + .ui-growl-message {
  color: #03a9f4 !important;
}
.ui-growl-image-warn + .ui-growl-message {
  color: #f9bf08 !important;
}
.ui-growl-image-error + .ui-growl-message {
  color: #f03369 !important;
}
