### ISSUE TITLE
Expanded attribute of Submenu is ignored

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/layouts#118]
Reported by a user;

http://forum.primefaces.org/viewtopic.php?f=42&t=47307

In summary, expanded property of submenu is ignored.

**Comment by morvael** [comment]
Could this be honored on other themes as well (for example south-street)?

**Comment by ZokiA** [comment]
Will this be fixed?

**Comment by mertsincan** [comment]
Fixed for next version; https://github.com/primefaces/ultima/issues/18
