### ISSUE TITLE
Volt 2.1.2 + Primefaces 6.0.6 Javascript Error

### ISSUE THREAD

**Issue by lcanalesmayo** [primefaces/layouts#129]
Hi,

When I use "menu" component from Volt template I got this Javascript Error:

Widget not available: Volt

This happens with Volt 2.1.2 an Primefaces 6.0.6. This doesn't happen with Volt 2.1 and Primefaces 5.3.17.

Forum link: http://forum.primefaces.org/viewtopic.php?f=29&t=47641

Thanks in advance.

**Comment by lcanalesmayo** [comment]
It worked changing layout.js.

Thanks

**Comment by mertsincan** [comment]
Thanks for the update!
