### ISSUE TITLE
Volt 2.1.2 + Primefaces 5.3.17 Execution error 

### ISSUE THREAD

**Issue by lcanalesmayo** [primefaces/layouts#130]
Hi,

when I try to use "menu" component of Volt template I'm getting this error:

java.lang.NoSuchMethodError: org.primefaces.context.ApplicationContext.getConfig()Lorg/primefaces/config/PrimeConfiguration;

It happens with Volt 2.1.2 and Primefaces 5.3.17, but not with Volt 2.1 and Primefaces 5.3.17.

Forum link: http://forum.primefaces.org/viewtopic.php?f=29&t=47643&p=147570#p147570

Thanks in advance.

**Comment by mertsincan** [comment]
I tried this issue with new layout version on 5.3.x and 6.0.x versions but, I couldn't replicate this issue.

**Comment by lcanalesmayo** [comment]
It worked changing layout.js.

Thanks

**Comment by mertsincan** [comment]
Thanks for the update!
