### ISSUE TITLE
Adamantium theme website: 404 not found

### ISSUE THREAD

**Issue by jxmai** [primefaces/layouts#136]
http://www.primefaces.org/layouts/adamantium

![snapshot3](https://cloud.githubusercontent.com/assets/10467831/20182907/043af838-a729-11e6-881c-eaa38516084a.png)

---

Actually **all the previous themes are down**. If I remember correctly, **the previous gen themes were end of sale not end of support**.  Why took all of them down ? Are they end of support now ?

![snapshot3](https://cloud.githubusercontent.com/assets/10467831/20183098/d0935e7a-a729-11e6-9872-0f81d0e5610f.png)

---

**I don't have a local copy of the adamantium theme's documentation at the moment. Removing the website suddenly without any forum post or warning is not appreciated :(**

**Comment by mertsincan** [comment]
Please try; www.primefaces.org/eos/adamantium

**Comment by jxmai** [comment]
@mertsincan The new link works. Thanks for your support :+1:
