### ISSUE TITLE
Sentinel Theme 1.3

### ISSUE THREAD

**Issue by aosama** [primefaces/layouts#27]
when the navigation bar on the left has a lot of items and is expanded i.e. longer in height than the entire browser window -- the dialogs displayed are then not correctly centered inside the browser window - 

The Y position of the dialog is calculated relevant to the entire page height including the not visible scrollabe area of the page
![screenshot from 2015-09-06 21 35 12](https://cloud.githubusercontent.com/assets/7742540/9706221/b37a0264-54df-11e5-92c0-d70179f2fc4b.png)

**Comment by mertsincan** [comment]
I couldn't replicate the issue. Please try with Sentinel demo; http://www.primefaces.org/sentinel/datatable.xhtml
![prime](https://cloud.githubusercontent.com/assets/11868120/9763438/28672e7e-5712-11e5-8ae4-667ed1fe618c.PNG)

Can you please attach a sample test.xhtml and testBean.java for us to replicate? And What PF-version are you using?

**Comment by mertsincan** [comment]
Please use sentinel forum.(http://forum.primefaces.org/viewforum.php?f=23)
