### ISSUE TITLE
Footer in Sentinel 1.3 and 1.3.1

### ISSUE THREAD

**Issue by aosama** [primefaces/layouts#28]
can you please post an example on how to correctly place a footer in sentinel theme

**Comment by mertsincan** [comment]
Sentinel Layout doesn't have a footer. But in template.xhtml, you can try with; 
```
<div id="layout-portlets-cover" class="fontRegular">
    <ui:insert name="content">
       Template
    </ui:insert>

    <div class="ContainerIndent TexAlCenter">
        <span class="Fs14 leaden fontRegular">PrimeFaces Sentinel  |   All rights reserved.</span>
    </div>
</div>
```
Next time, please use sentinel forum.(http://forum.primefaces.org/viewforum.php?f=23)
