### ISSUE TITLE
Chrome issue with any of the commercial themes/layouts

### ISSUE THREAD

**Issue by madsbredholt** [primefaces/layouts#51]
Hi

I get the following bug (ref screenshot and stacktrace ) when viewing  any of the commercial themes with chrome.

1) Screenshot is from the following url: http://www.primefaces.org/modena/sample.xhtml
2) Chrome details: Version 46.0.2490.80 (64-bit)
3) OS details: Ubuntu 14.04 TLS

//screenshot
![theme-screenshot-bug](https://cloud.githubusercontent.com/assets/647705/11296340/d25503a6-8f71-11e5-841b-d045928277a1.png)

//chrome console stacktrace
Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.primefaces.org/modena/images/ui-bg_highlight-soft_100_eeeeee_1x100.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.primefaces.org/modena/images/ui-bg_gloss-wave_35_f6a828_500x100.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.primefaces.org/modena/images/ui-bg_glass_65_ffffff_1x400.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.primefaces.org/modena/images/ui-bg_glass_100_fdf5ce_1x400.png Failed to load resource: the server responded with a status of 404 (Not Found)

Can you help ?

Regards
Mads

**Comment by mertsincan** [comment]
Thanks for the screenshot and other information. Can you please try other layouts on  Ubuntu - Chrome?

**Comment by madsbredholt** [comment]
Hi

Here are screenshots of rio,adamtium, sentinal and spark.

![rio-layout](https://cloud.githubusercontent.com/assets/7994132/11332043/2e921418-91c2-11e5-8f7d-026e97305980.png)
![sentinel-layout](https://cloud.githubusercontent.com/assets/7994132/11332041/2e90d83c-91c2-11e5-882e-d0a4823bc9dc.png)
![spark-layout](https://cloud.githubusercontent.com/assets/7994132/11332042/2e915fc8-91c2-11e5-9d8e-546ebd64160d.png)
![adantium-layout](https://cloud.githubusercontent.com/assets/7994132/11332040/2e90a54c-91c2-11e5-8c11-c0f699d97e61.png)


Regards
Mads

**Comment by mertsincan** [comment]
Thank you, Mads. We will work on this issue and get back to you.

**Comment by mertsincan** [comment]
We couldn't replicate this issue.
