### ISSUE TITLE
modena 1.0.3 form input element lost their background colour making the less "usable"

### ISSUE THREAD

**Issue by gatapia** [primefaces/layouts#94]
usability of input/selects/multiselects suffers in modena 1.0.3 update.  They have lost their background colours (and borders) making them look like labels:

![image](https://cloud.githubusercontent.com/assets/135965/16503228/8002e7fa-3f55-11e6-8f73-873f133ceb54.png)
> image from your modena demo

![image](https://cloud.githubusercontent.com/assets/135965/16503430/5c2393f6-3f56-11e6-8526-81276829603d.png)
> image of table filters from my dummy app

I think a standard select/input box style control is still needed to give the user an experience that is standard.

I have hacked this to look a litlle better using the following CSS:
```
input.ui-widget, .ui-dropdown {
  border: solid 1px #c0c0c0;
  background-color: #fff;
}

```

**Comment by mertsincan** [comment]
This isn't a bug. We made some changes on background-color and border values of our input component for compatibility with material input.
